name: contra-c19
channels:
- conda-forge
dependencies:
- python>=3.11
- ipython
- jupyter
- jupyterlab
- numpy
- pandas
- pyarrow
- matplotlib
- mplleaflet
- ipympl
- seaborn
- plotnine
- pyproj
- requests
- openpyxl
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- xgboost
- optuna
- shap